Fix forgotten settingsdir=None in gajim.py (closes #26)
Causes:
Traceback (most recent call last):
  File "./keysync", line 110, in <module>
    main()
  File "./keysync", line 87, in main
    otrapps.util.merge_keydicts(keydict, properties.parse())
TypeError: parse() takes exactly 1 argument (0 given)